[project_name]
data = 'dismod_at'

[directory]
project_directory = '.'
rst_directory     = 'build/rst'
html_directory    = 'build/html'
tex_directory     = 'build/tex'

[root_file]
default = 'doc.xrst'
dev     = 'devel/devel.xrst'

[preamble]
rst_substitution = '''
.. |space| unicode:: 0xA0
.. |tab| replace:: |space| |space| |space|
'''
latex_macro = [
   '\newcommand{\B}[1]{ {\bf #1} }' ,
   '\newcommand{\R}[1]{ {\rm #1} }' ,
   '\newcommand{\W}[1]{ \; #1 \; }'
]

[project_dictionary]
data = [ '''
   avg
   avgint
   bilinear
   bnd
   const
   cov
   cpp
   cppad
   csv
   cv
   dage
   db
   dict
   dismod
   dismodat
   dtime
   eqnarray
   hes
   init
   ipopt
   laplace
   meas
   mulcov
   mulstd
   multiplier
   nan
   nowrap
   nslist
   obj
   pini
   py
   rho
   sh
   sim
   sincidence
   smoothings
   sqlite
   std
   str
   struct
   subgroup
   th
   var
   vec
''' ]
